### PR TITLE
Add monacoin/ziftrCOIN

### PR DESCRIPTION
**Pull request by scmorse**
I saw from the existing pull requests that `22'` is reserved for Monacoin, so I added ziftrCOIN after it.

ZiftrCOIN is more of a coupon than a digital currency, intended to be part of GOCOIN's customer rewards program, after our recent merger. Our mobile wallet, ziftrWALLET (http://www.ziftrwallet.com/), is in open beta. You may download it on the Android App store. We have nearly finished implementing HD wallets.

### CODE REVIEW

**Comment by erasmospunk** [comment]
Keep in mind that there are open pull requests #25, #30 and #33. The index `22` is used by Monacoin.

**Comment by scmorse** [comment]
@erasmospunk Updated to use 27, which seems to be unused. When will the PRs you mentioned and this one be merged?

**Comment by erasmospunk** [comment]
Notice that index `27` should be `0x8000001B` in hex.

**Comment by scmorse** [comment]
@erasmospunk Whoops! Updated.

**Comment by erasmospunk** [comment]
You can close this pull request as I added this change to https://github.com/satoshilabs/docs/pull/25/files

**Comment by prusnak** [comment]
Closing. Merged via #25

**Pull request closed without merging**
