### PR TITLE
Clarifying Copay purpose field 48 and fixing a few typos

### PR DESCRIPTION
**Pull request by jonathancross**

### CODE REVIEW

**Comment by prusnak** [comment]
The change from BIP-48 to SLIP-49 is wrong. Copay indeed uses BIP-48 (because they use m/48' in their paths), but they never invested any time to document it.

Otherwise it's a good change.

**Comment by luke-jr** [comment]
There is no such thing as BIP 48 at all.

**Comment by prusnak** [comment]
> There is no such thing as BIP 48 at all.

I know. I told them to write it, but they never bothered.

As per BIP-43 they are using something documented in BIP-48, because they are using m/48' path - that they did not bother to document it, is their fight, not mine.

**Comment by jonathancross** [comment]
Thanks for the correction, now updated.
Since BIP48 doesn't exist, I mentioned that the number `48` is used for the BIP43 "Purpose field".  Please let me know if this is acceptable.

**Comment by prusnak** [comment]
Splendid. Thank you, both!

**Pull request merged**
