### PR TITLE
added support for DogecoinDark wallet

### PR DESCRIPTION
**Pull request by doged**
bip44 support for DogecoinDark coinomi wallet.

### CODE REVIEW

**Comment by erasmospunk** [comment]
Notice that index `77` should be `0x8000004d` in hex.

**Comment by doged** [comment]
fixed

**Comment by erasmospunk** [comment]
You can close this pull request as I added this change to https://github.com/satoshilabs/docs/pull/25/files

**Comment by prusnak** [comment]
Closing. Merged via #25

**Pull request closed without merging**
