### PR TITLE
Added Rubycoin, Uro, Digitalcoin, Cannacoin

### PR DESCRIPTION
**Pull request by FuzzyHobbit**
https://github.com/FuzzyHobbit/coinomi-android/commit/b35614fe005eb85c36b0b97562ae4015b0922928
https://github.com/FuzzyHobbit/coinomi-android/commit/4aaf47b19821f6a94131be1fe218674bfc3175c8

### CODE REVIEW

**Comment by erasmospunk** [comment]
There is a conflict now.

For about a month ago we accepted a pull request to with, among others, Rubycoin support. It uses index 16, and the pull request #17 from @guruvan conflicts with this index.

To confuse things even more, @esotericizm made a pull request that actually adds support to DigiByte (https://github.com/Coinomi/coinomi-android/pull/16/files) and it uses index 20.

From this pull request, only Rubycoin, Digitalcoin, Cannacoin made it to the Coinomi wallet so I suggest closing this one and modify the list as follows:

16    0x80000010 Rubycoin
17    0x80000011 ___unused___
18    0x80000012 Digitalcoin
19    0x80000013 Cannacoin
20    0x80000014 DigiByte

@prusnak, @esotericizm, @guruvan, @FuzzyHobbit what do you think?

**Comment by guruvan** [comment]
not picky myself about the number, just so long as it's decided and set so we can integrate DGB into our wallet. :)

**Comment by prusnak** [comment]
Aw, crap. :-( Agreed. 

@erasmospunk Can you please create a new pull request that will solve this mess? I'll merge it ASAP and close this one.

**Comment by erasmospunk** [comment]
@guruvan I also don't care as long as users don't lose their money! Nice wallet btw.
@prusnak doing it now. I also missed it, next time we will not release a build with a coin support until there is an allocated index.

**Comment by guruvan** [comment]
@erasmospunk all good either way...we're just placeholding DGB at 9999 for the moment - and Thanks :) 

@prusnak (hate to hijack - sent you mail to stick@satoshilabs - will you get that?)

**Comment by erasmospunk** [comment]
OK, created PR #18 
I guess we can close this one.

@prusnak thanks for the fast response!

**Comment by prusnak** [comment]
Merged in #18. Closing this one.

**Pull request closed without merging**
