### PR TITLE
Reserving level two index for additional coins

### PR DESCRIPTION
**Pull request by dangershony**

### CODE REVIEW

**Comment by dangershony** [comment]
Thanks that was fast.

**Comment by prusnak** [comment]
I need to deploy it manually, which I just did. I am thinking of moving slips into a separate repo which will update automatically via Github pages.

**Comment by dangershony** [comment]
Excellent idea I'll most probably need to added more coins to the list in the future.

**Comment by prusnak** [comment]
moved here: https://github.com/satoshilabs/slips

**Comment by dangershony** [comment]
Cool thanks will the bitcoin bip repo also needs to be changed?
https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki

**Comment by prusnak** [comment]
I already sent a pull request, which is pending.

--
Best Regards / S pozdravom,
 
Pavol Rusnak <stick@gk2.sk>
 
 
On Mon, Feb 1, 2016, at 05:02 PM, Dan Gershony wrote:
> Cool thanks will the bitcoin bip repo also needs to be changed?
> https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki


> —
> Reply to this email directly or view it on GitHub[1]. 


>  
 


Links:

  1. https://github.com/satoshilabs/docs/pull/66#issuecomment-178043164

**Pull request merged**
