### PR TITLE
Adding SLIP 0015

### PR DESCRIPTION
**Pull request by runn1ng**
I have added code examples directly into the slip. Not sure if great idea, but I don't want to add python files to the docs either.

### CODE REVIEW

**Comment by slush0** [comment]
Better to publish python files to github repo and link it from SLIP as reference implementation.

**Comment by luke-jr** [comment]
This looks more like it should be a BIP?

**Comment by slush0** [comment]
So far this is vendor specific (=Trezor). We don't want to slow down own development by advocating internal structures of our own app. If we prove the design is successful and other wallets will start using it as well, they don't need to refer to BIP number (the same situation as pools started to use Stratum without BIP specification).

To say it clearly, I'm exhausted by never ending discussions in BIP pull requests, so until it is something related to Bitcoin itself, I don't care anymore. Life is too short to flamewars.

**Comment by runn1ng** [comment]
Yeah, like @slush0 said. Especially the parts about deriving account keys are specific for hierarchical hardware wallets. 

Also it caters quite specifically to our needs in mytrezor - for example we don't label specific transactions, because we thought it's redundant (as you can label the outputs), but other developers might  disagree 

However if any other applications use this format, that would be great.

**Comment by jonathancross** [comment]
Would love to see a BIP if anyone has the energy/nerves/skills to make it happen.  We need an Open standard for HD wallet metadata.

**Pull request merged**
