### PR TITLE
Fix udev for Arch Linux, fix firmware verification URL

### PR DESCRIPTION
**Pull request by stevesbrain**
The USB subsystem line breaks TREZOR on Arch linux.

### CODE REVIEW

**Comment by prusnak** [comment]
That is really weird. Could you consult with Arch people why this breaks their udev?

**Comment by stevesbrain** [comment]
@prusnak I can have a chat and see what I can find out - will get back to you when I've heard :)

**Comment by almindor** [comment]
Works for me on latest arch

**Comment by prusnak** [comment]
@stevesbrain please reopen if still not working

**Pull request closed without merging**
