### PR TITLE
Update slip-0044.rst

### PR DESCRIPTION
**Pull request by btcdrak**
Added Viacoin (VIA) and ClearingHouse (XCH)

viacoin.org
clearinghouse.io

### CODE REVIEW

**Comment by prusnak** [comment]
a) testnet is not necessary - all altcoins should use the same value (1)
b) can you please tell us which wallet implements bip44 and supports added coins?

**Comment by btcdrak** [comment]
Thanks for questions

a) Why is a testnet not necessary? We actively use testnet, unlike most altcoin. Why does Bitcoin have a separate testnet value if it's not necessary?

b) [Vialectrum](https://github.com/vialectrum/vialectrum) 2.0 will support bip44 based on Electrum 2.0.
clearwallet.co for XCH (clearinghouse) will implement BIP44.

**Comment by prusnak** [comment]
a) i meant that assigning a separate value for each altcoin testnet is not necessary and that using value 1 for all altcoins is OK
b) please rework your pull request - value 13/0x8000000d is already used by Mazacoin

**Comment by btcdrak** [comment]
redone in #14

**Pull request closed without merging**
